"""@aidw build command - Implement from plan."""

import logging
import time
from typing import Any

from aidw.commands.base import BaseCommand
from aidw.database import Session
from aidw.github.context import WorkflowContext
from aidw.github.progress import ProgressReporter, ProgressStep, ProgressTracker, StepStatus
from aidw.sandbox import SandboxExecutor
from aidw.server.webhook import ParsedCommand

logger = logging.getLogger(__name__)


class BuildCommand(BaseCommand):
    """Implement from the approved plan."""

    command_name = "build"
    prompt_template = "build.md"

    def get_progress_steps(self) -> list[ProgressStep]:
        """Return the progress steps for the build workflow.

        Returns:
            List of five steps: read plan, implement, test, document, and push changes
        """
        return [
            ProgressStep("Read plan"),
            ProgressStep("Implement"),
            ProgressStep("Test"),
            ProgressStep("Document"),
            ProgressStep("Push changes"),
        ]

    async def run_workflow(
        self,
        session: Session,
        context: WorkflowContext,
        executor: SandboxExecutor,
        progress: ProgressReporter,
        tracker: ProgressTracker,
    ) -> dict[str, Any]:
        """Build the full implementation from the approved plan.

        Workflow steps:
        1. Read plan - Verifies plan file exists and renders prompt with plan content
        2. Implement - Runs Claude Code to implement all code changes from the plan
        3. Test - Claude Code writes and runs tests for the implementation
        4. Document - Claude Code updates relevant documentation
        5. Push changes - Updates PR title/body to remove [WIP] and mark as ready

        Args:
            session: Database session tracking this workflow
            context: Workflow context with PR, issue, and plan information
            executor: Sandbox executor for running Claude Code
            progress: Progress reporter for posting updates to GitHub
            tracker: Progress tracker for managing step status

        Returns:
            Dictionary with pr_number and pr_url of the updated PR

        Raises:
            RuntimeError: If plan file is missing or Claude Code fails
        """
        # Step 1: Read plan
        await self._update_step(tracker, progress, 0, StepStatus.RUNNING)
        start = time.time()

        # Check plan file exists
        plan_exists = await executor.file_exists(context.plan_path)
        if not plan_exists:
            raise RuntimeError(f"{context.plan_path} not found. Run `@aidw plan` first.")

        # Render prompt
        prompt = await self._render_prompt(context)

        await self._update_step(
            tracker, progress, 0, StepStatus.COMPLETED, int(time.time() - start)
        )

        # Step 2-4: Implement, test, document (all done by Claude Code)
        await self._update_step(tracker, progress, 1, StepStatus.RUNNING)
        start = time.time()

        # Run Claude Code
        result = await executor.run_claude(prompt)

        if not result.success:
            raise RuntimeError(f"Claude Code failed: {result.error}")

        # Mark implementation steps complete
        await self._update_step(
            tracker, progress, 1, StepStatus.COMPLETED, int(time.time() - start)
        )
        await self._update_step(tracker, progress, 2, StepStatus.COMPLETED)
        await self._update_step(tracker, progress, 3, StepStatus.COMPLETED)

        # Step 5: Push changes
        await self._update_step(tracker, progress, 4, StepStatus.RUNNING)
        start = time.time()

        # These are guaranteed to be set by base.execute() before run_workflow is called
        assert self.github is not None
        assert session.pr_number is not None

        # Update PR description
        pr_body = f"""## Implementation for #{context.issue.number}

This PR implements issue #{context.issue.number}: {context.issue.title}

**Artifacts:**
- [`{context.plan_path}`]({context.plan_path}) - Implementation plan
- Implementation code
- Tests
- Documentation updates

**Review:**
- Comment `@aidw iterate <feedback>` to request changes
- Approve and merge when ready

---
_Generated by AIDW | Session: {session.id}_
"""

        await self.github.update_pull_request(
            repo=session.repo,
            pr_number=session.pr_number,
            title=context.issue.title,  # Remove [WIP] prefix
            body=pr_body,
        )

        await self._update_step(
            tracker, progress, 4, StepStatus.COMPLETED, int(time.time() - start)
        )

        return {
            "pr_number": session.pr_number,
            "pr_url": f"https://github.com/{session.repo}/pull/{session.pr_number}",
        }

    async def execute_manual(self, repo: str, pr: int, instruction: str = "") -> None:
        """Execute build command manually from CLI or script.

        Args:
            repo: Repository in owner/name format
            pr: PR number containing the plan to implement
            instruction: Optional additional instruction to guide the implementation
        """
        cmd = ParsedCommand(
            command=self.command_name,
            instruction=instruction,
            author="manual",
            body=f"@aidw {self.command_name} {instruction}".strip(),
            repo=repo,
            issue_number=pr,
            pr_number=pr,
            comment_id=0,
        )
        await self.execute(cmd)


# Singleton instance
build_command = BuildCommand()
