"""@aidw build command - Implement from plan."""

import logging
import time
from typing import Any

from aidw.commands.base import BaseCommand
from aidw.database import Session
from aidw.github.context import WorkflowContext
from aidw.github.progress import ProgressReporter, ProgressStep, ProgressTracker, StepStatus
from aidw.sandbox import SandboxExecutor
from aidw.server.webhook import ParsedCommand

logger = logging.getLogger(__name__)


class BuildCommand(BaseCommand):
    """Implement from the approved plan."""

    command_name = "build"
    prompt_template = "build.md"

    def get_progress_steps(self) -> list[ProgressStep]:
        return [
            ProgressStep("Read plan"),
            ProgressStep("Implement"),
            ProgressStep("Test"),
            ProgressStep("Document"),
            ProgressStep("Push changes"),
        ]

    async def run_workflow(
        self,
        session: Session,
        context: WorkflowContext,
        executor: SandboxExecutor,
        progress: ProgressReporter,
        tracker: ProgressTracker,
    ) -> dict[str, Any]:
        """Build the implementation from the plan."""
        # Step 1: Read plan
        await self._update_step(tracker, progress, 0, StepStatus.RUNNING)
        start = time.time()

        # Check PLAN.md exists
        plan_exists = await executor.file_exists("PLAN.md")
        if not plan_exists:
            raise RuntimeError("PLAN.md not found. Run `@aidw plan` first.")

        # Render prompt
        prompt = await self._render_prompt(context)

        await self._update_step(
            tracker, progress, 0, StepStatus.COMPLETED, int(time.time() - start)
        )

        # Step 2-4: Implement, test, document (all done by Claude Code)
        await self._update_step(tracker, progress, 1, StepStatus.RUNNING)
        start = time.time()

        # Run Claude Code
        result = await executor.run_claude(prompt)

        if not result.success:
            raise RuntimeError(f"Claude Code failed: {result.error}")

        # Mark implementation steps complete
        await self._update_step(
            tracker, progress, 1, StepStatus.COMPLETED, int(time.time() - start)
        )
        await self._update_step(tracker, progress, 2, StepStatus.COMPLETED)
        await self._update_step(tracker, progress, 3, StepStatus.COMPLETED)

        # Step 5: Push changes
        await self._update_step(tracker, progress, 4, StepStatus.RUNNING)
        start = time.time()

        # Update PR description
        pr_body = f"""## Implementation for #{context.issue.number}

This PR implements issue #{context.issue.number}: {context.issue.title}

**Artifacts:**
- `PLAN.md` - Implementation plan
- Implementation code
- Tests
- Documentation updates

**Review:**
- Comment `@aidw iterate <feedback>` to request changes
- Approve and merge when ready

---
_Generated by AIDW | Session: {session.id}_
"""

        await self.github.update_pull_request(
            repo=session.repo,
            pr_number=session.pr_number,
            title=context.issue.title,  # Remove [WIP] prefix
            body=pr_body,
        )

        await self._update_step(
            tracker, progress, 4, StepStatus.COMPLETED, int(time.time() - start)
        )

        return {
            "pr_number": session.pr_number,
            "pr_url": f"https://github.com/{session.repo}/pull/{session.pr_number}",
        }

    async def execute_manual(self, repo: str, pr: int, instruction: str = "") -> None:
        """Execute build command manually."""
        cmd = ParsedCommand(
            command=self.command_name,
            instruction=instruction,
            author="manual",
            body=f"@aidw {self.command_name} {instruction}".strip(),
            repo=repo,
            issue_number=pr,
            pr_number=pr,
            comment_id=0,
        )
        await self.execute(cmd)


# Singleton instance
build_command = BuildCommand()
