"""@aidw oneshot command - Full automation from issue to PR."""

import logging
import time
from typing import Any

from aidw.commands.base import BaseCommand
from aidw.database import Session
from aidw.github.context import WorkflowContext
from aidw.github.progress import ProgressReporter, ProgressStep, ProgressTracker, StepStatus
from aidw.sandbox import SandboxExecutor
from aidw.server.webhook import ParsedCommand

logger = logging.getLogger(__name__)


class OneshotCommand(BaseCommand):
    """Full automation: plan, implement, test, document, and create PR."""

    command_name = "oneshot"
    prompt_template = "oneshot.md"

    def get_progress_steps(self) -> list[ProgressStep]:
        return [
            ProgressStep("Analyze issue"),
            ProgressStep("Create plan"),
            ProgressStep("Implement"),
            ProgressStep("Test"),
            ProgressStep("Document"),
            ProgressStep("Create PR"),
        ]

    async def run_workflow(
        self,
        session: Session,
        context: WorkflowContext,
        executor: SandboxExecutor,
        progress: ProgressReporter,
        tracker: ProgressTracker,
    ) -> dict[str, Any]:
        """Run the complete workflow."""
        # Step 1: Analyze issue
        await self._update_step(tracker, progress, 0, StepStatus.RUNNING)
        start = time.time()

        # Render prompt
        prompt = await self._render_prompt(context)

        await self._update_step(
            tracker, progress, 0, StepStatus.COMPLETED, int(time.time() - start)
        )

        # Steps 2-5: Plan, implement, test, document (all done by Claude Code)
        await self._update_step(tracker, progress, 1, StepStatus.RUNNING)
        start = time.time()

        # Run Claude Code
        result = await executor.run_claude(prompt)

        if not result.success:
            raise RuntimeError(f"Claude Code failed: {result.error}")

        # Mark all implementation steps complete
        elapsed = int(time.time() - start)
        await self._update_step(tracker, progress, 1, StepStatus.COMPLETED, elapsed // 4)
        await self._update_step(tracker, progress, 2, StepStatus.COMPLETED, elapsed // 4)
        await self._update_step(tracker, progress, 3, StepStatus.COMPLETED, elapsed // 4)
        await self._update_step(tracker, progress, 4, StepStatus.COMPLETED, elapsed // 4)

        # Step 6: Create PR
        await self._update_step(tracker, progress, 5, StepStatus.RUNNING)
        start = time.time()

        # These are guaranteed to be set by base.execute() before run_workflow is called
        assert self.sandbox_manager is not None
        assert self.github is not None
        assert session.branch is not None

        # Push branch first (required before creating PR)
        await self.sandbox_manager.push_changes(executor.instance, session.branch)

        # Create PR
        pr_body = f"""## Closes #{context.issue.number}

This PR fully implements issue #{context.issue.number}: {context.issue.title}

**Artifacts:**
- [`{context.plan_path}`]({context.plan_path}) - Implementation plan
- Implementation code
- Tests
- Documentation updates

**Review:**
- Comment `@aidw iterate <feedback>` to request changes
- Approve and merge when ready

---
_Generated by AIDW (oneshot) | Session: {session.id}_
"""

        pr = await self.github.create_pull_request(
            repo=session.repo,
            title=context.issue.title,
            body=pr_body,
            head=session.branch,
            base=await self.github.get_default_branch(session.repo),
            draft=False,  # Oneshot creates a ready PR
        )

        await self._update_step(
            tracker, progress, 5, StepStatus.COMPLETED, int(time.time() - start)
        )

        return {
            "pr_number": pr.number,
            "pr_url": pr.url,
        }

    async def execute_manual(self, repo: str, issue: int, instruction: str = "") -> None:
        """Execute oneshot command manually."""
        cmd = ParsedCommand(
            command=self.command_name,
            instruction=instruction,
            author="manual",
            body=f"@aidw {self.command_name} {instruction}".strip(),
            repo=repo,
            issue_number=issue,
            pr_number=None,
            comment_id=0,
        )
        await self.execute(cmd)


# Singleton instance
oneshot_command = OneshotCommand()
