"""@aidw plan command - Create initial implementation plan."""

import logging
import time
from typing import Any

from aidw.commands.base import BaseCommand
from aidw.database import Session
from aidw.github.context import WorkflowContext
from aidw.github.progress import ProgressReporter, ProgressStep, ProgressTracker, StepStatus
from aidw.sandbox import SandboxExecutor
from aidw.server.webhook import ParsedCommand

logger = logging.getLogger(__name__)


class PlanCommand(BaseCommand):
    """Create an implementation plan for an issue."""

    command_name = "plan"
    prompt_template = "plan.md"

    def get_progress_steps(self) -> list[ProgressStep]:
        return [
            ProgressStep("Analyze issue"),
            ProgressStep("Create plan"),
            ProgressStep("Create PR"),
        ]

    async def run_workflow(
        self,
        session: Session,
        context: WorkflowContext,
        executor: SandboxExecutor,
        progress: ProgressReporter,
        tracker: ProgressTracker,
    ) -> dict[str, Any]:
        """Create a plan and PR."""
        # Compute plan path from issue title
        context.plan_path = self._get_plan_path(context)

        # Step 1: Analyze issue
        await self._update_step(tracker, progress, 0, StepStatus.RUNNING)
        start = time.time()

        # Render prompt
        prompt = await self._render_prompt(context)

        await self._update_step(
            tracker, progress, 0, StepStatus.COMPLETED, int(time.time() - start)
        )

        # Step 2: Create plan
        await self._update_step(tracker, progress, 1, StepStatus.RUNNING)
        start = time.time()

        # Run Claude Code
        result = await executor.run_claude(prompt)

        if not result.success:
            raise RuntimeError(f"Claude Code failed: {result.error}")

        logger.info(f"Claude Code completed. Output length: {len(result.output) if result.output else 0}")

        # Commit any uncommitted changes (Claude may have already committed)
        await executor.commit_changes(f"Add implementation plan for issue #{context.issue.number}")

        # Verify plan file was created
        if not await executor.file_exists(context.plan_path):
            raise RuntimeError(f"Claude Code completed but {context.plan_path} was not created. Check the Claude output.")

        await self._update_step(
            tracker, progress, 1, StepStatus.COMPLETED, int(time.time() - start)
        )

        # Step 3: Create PR
        await self._update_step(tracker, progress, 2, StepStatus.RUNNING)
        start = time.time()

        # These are guaranteed to be set by base.execute() before run_workflow is called
        assert self.sandbox_manager is not None
        assert self.github is not None
        assert session.branch is not None

        # Push branch first (required before creating PR)
        await self.sandbox_manager.push_changes(executor.instance, session.branch)

        # Create PR
        pr_body = f"""## Implementation Plan for #{context.issue.number}

This PR contains an implementation plan for issue #{context.issue.number}: {context.issue.title}

**Next steps:**
- Review the [`{context.plan_path}`]({context.plan_path}) file
- Comment `@aidw refine <feedback>` to iterate on the plan
- Comment `@aidw build` when ready to implement

---
_Generated by AIDW | Session: {session.id}_
"""

        pr = await self.github.create_pull_request(
            repo=session.repo,
            title=f"[WIP] {context.issue.title}",
            body=pr_body,
            head=session.branch,
            base=await self.github.get_default_branch(session.repo),
            draft=True,
        )

        await self._update_step(
            tracker, progress, 2, StepStatus.COMPLETED, int(time.time() - start)
        )

        return {
            "pr_number": pr.number,
            "pr_url": pr.url,
        }

    async def execute_manual(self, repo: str, issue: int, instruction: str = "") -> None:
        """Execute plan command manually."""
        cmd = ParsedCommand(
            command=self.command_name,
            instruction=instruction,
            author="manual",
            body=f"@aidw {self.command_name} {instruction}".strip(),
            repo=repo,
            issue_number=issue,
            pr_number=None,
            comment_id=0,
        )
        await self.execute(cmd)


# Singleton instance
plan_command = PlanCommand()
